### ISSUE TITLE
Siglent: read waveform in one or more blocks and support larger sample depths

### ISSUE THREAD

**Issue by hansemro** [ngscopeclient/scopehal#789]
## Issue Description

SiglentSCPIOscilloscope does not support reading waveform data in blocks, which prevents many scopes from supporting sample depths larger than the the data block size.

For reference, on SDS2000X+/SDS2000XHD/SDS5000X/SDS6000:
- we can get/set data block size (in number of samples) with `:WAVEFORM:POINT`.
    - If the value is 0, then the set the block size to its maximum.
- we can get the maximum block size with `:WAVEFORM:MAXPOINT?`.

Even for smaller sample depths, reading in multiple blocks will be required if the set block size is smaller!

## Relevant Development Work

- Multi-block read implementation in a python script for SDS2000X+: https://gist.github.com/hansemro/311107a5bf4a5e5733b729a947f09b0b#file-sds2000xp_read_waveforms-py-L284-L306
- Dev branch for SDS2000X+ that addresses issue: https://github.com/hansemro/scopehal/tree/siglent-sds2000xp-read-blocks-dev
    - supports 10M/20M,100M/200M sample depths
    - supports 8- and 10-bit ADC modes

Preview of siglent-sds2000xp-read-blocks-dev branch:

https://github.com/glscopeclient/scopehal/assets/40348686/037d9182-9cfc-494f-8022-ed5e07c03035

**Comment by azonenberg** [comment]
Fixed in latest by @fredzo
