### ISSUE TITLE
SIGLENT SDS5104X ReadWaveformBlock: invalid length format

### ISSUE THREAD

**Issue by codepox** [ngscopeclient/scopehal#836]
Problem reading Waveform on SIGLENT SDS5104X running latest software V0.98R2
ngscopeclient 0.1-b64aa4e

[ngscopeclient --debug --trace SCPISocketTransport.txt](https://github.com/ngscopeclient/scopehal/files/13779584/ngscopeclient.--debug.--trace.SCPISocketTransport.txt)

**Comment by azonenberg** [comment]
Fixed in bd79a0e71d623c051c4b51ccefe942a631d4334c
