### ISSUE TITLE
Changing units causes histogram to either not display data or to crash

### ISSUE THREAD

**Issue by mx-shift** [ngscopeclient/scopehal#881]
Built at 58af58e on Fedora 39.  nVidia Quadro P600 with nVidia 545.29.06 drivers.

If I import [00.0.revolution1.500_flashfloppy_v341.csv](https://github.com/ngscopeclient/scopehal-apps/files/14317939/00.0.revolution1.500_flashfloppy_v341.csv), I get a waveform display with the Y units default to volts.  I can create a histogram and get data that appears to be correct.

The Y units are actually phase error measured in clock ticks so I tried to guess a more appropriate unit.  Choosing either UI or dimensionless before creating a histogram, the waveform renders fine but the histogram is blank:
![image](https://github.com/ngscopeclient/scopehal/assets/9454487/22e4dde5-6fc9-4edd-bbf2-9f5484df68d9)

If I change the Y units to UI or dimensionless after opening a histogram, I get a crash:
```
mxshift@eps-conduit .../build/src/ngscopeclient ❯ ./ngscopeclient
Floating point exception (core dumped)
```

**Comment by azonenberg** [comment]
Moved to scopehal as this is an issue (or series of issues) with the histogram filter.

**Comment by azonenberg** [comment]
The reason nothing is displayed is that it's trying to create a histogram with only one bin (and apparently rendering breaks in that edge case).

```
[HistogramFilter::Refresh] nmin = -24 UI, nmax = 2 UI
[HistogramFilter::Refresh] Calculated: 1 bins
[HistogramFilter::Refresh] Bin size: 28.6 UI
```

**Comment by azonenberg** [comment]
And it turns out the reason for this is that autoranging does not actually automatically calculate the bin size. You're asking for 100-UI wide bins by default so it's getting very confused.

Fix pending, will need to automatically choose a sane bin size if in autorange mode.
